
name        = "Gallery Deluxe"
license     = "MIT"
licenselink = "https://github.com/bep/gallerydeluxe/blob/main/LICENSE"
description = "Fast gallery suitable for lots of images."
homepage    = "https://github.com/bep/gallerydeluxe"
demosite    = "https://staticbattery.com/"
tags        = ["gallery", "sass"]
min_version = "0.129.0"
[author]
  name     = "Bj√∏rn Erik Pedersen"
  homepage = "http://bep.is"
